package uz.jahonov.ktormonitor.data

import androidx.room.ConstructedBy
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverter
import androidx.room.TypeConverters
import androidx.room.Update
import androidx.room.Upsert
import androidx.sqlite.SQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.flow.Flow
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.MapSerializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.json.Json

@Database(entities = [CallEntity::class], version = 2)
@ConstructedBy(KtorMonitorDatabaseConstructor::class)
@TypeConverters(HeadersConverter::class)
internal abstract class KtorMonitorDatabase : RoomDatabase() {
    abstract fun calls(): CallDao
}

// Generated by Room for each target.
@Suppress("KotlinNoActualForExpect")
internal expect object KtorMonitorDatabaseConstructor : RoomDatabaseConstructor<KtorMonitorDatabase> {
    override fun initialize(): KtorMonitorDatabase
}

/**
 * The history is disposable: a schema change, either way (an older library after a newer one), starts
 * it afresh instead of migrating. Every change of [CallEntity] needs a new version; the exported
 * schemas in `ktor-monitor/schemas` show one that was forgotten.
 */
internal fun RoomDatabase.Builder<KtorMonitorDatabase>.buildKtorMonitorDatabase(): KtorMonitorDatabase =
    setDriver(sqliteDriver())
        .setQueryCoroutineContext(Dispatchers.IO)
        // Covers a downgrade too. Adding fallbackToDestructiveMigrationOnDowngrade would undo this:
        // it makes a migration required again for an upgrade.
        .fallbackToDestructiveMigration(dropAllTables = true)
        .build()

internal const val KTOR_MONITOR_DB = "ktormonitor.db"

/** The platform's SQLite on Android, a bundled one on iOS. */
internal expect fun sqliteDriver(): SQLiteDriver

/**
 * Bodies hold the bytes kept; the sizes are what the bodies really had. The bodies are the last
 * columns: SQLite reads a row's columns in order, and one after a large body would make every list
 * query walk through the body's pages.
 */
@Entity(tableName = "call", indices = [Index("requestTime")])
internal data class CallEntity(
    @PrimaryKey val id: String,
    val groupId: String,
    val attempt: Int,
    val method: String,
    val url: String,
    val requestTime: Long,
    val requestHeaders: Map<String, List<String>>,
    val requestContentType: String?,
    val requestBodySize: Long?,
    val protocol: String?,
    val responseCode: Int?,
    val responseTime: Long?,
    val responseHeaders: Map<String, List<String>>,
    val responseContentType: String?,
    val responseBodySize: Long?,
    val error: String?,
    val requestBody: ByteArray?,
    val responseBody: ByteArray?,
)

/** A list row: everything but the headers and bodies. */
internal data class CallSummaryRow(
    val id: String,
    val groupId: String,
    val attempt: Int,
    val method: String,
    val url: String,
    val requestTime: Long,
    val requestContentType: String?,
    val requestBodySize: Long?,
    val protocol: String?,
    val responseCode: Int?,
    val responseTime: Long?,
    val responseContentType: String?,
    val responseBodySize: Long?,
    val error: String?,
)

@Dao
internal interface CallDao {
    @Upsert
    suspend fun upsert(call: CallEntity)

    /** Does nothing when the call is gone. */
    @Update
    suspend fun update(call: CallEntity)

    /**
     * Newest first. [query] matches the URL, method, status code and both bodies, ignoring letter
     * case; `%`, `_` and `\` in it must be escaped with `\`. An empty query matches everything.
     */
    @Query(
        """
        SELECT id, groupId, attempt, method, url, requestTime, requestContentType, requestBodySize, protocol,
            responseCode, responseTime, responseContentType, responseBodySize, error
        FROM call
        WHERE :query = ''
            OR url LIKE '%' || :query || '%' ESCAPE '\'
            OR method LIKE '%' || :query || '%' ESCAPE '\'
            OR CAST(responseCode AS TEXT) LIKE '%' || :query || '%' ESCAPE '\'
            OR CAST(requestBody AS TEXT) LIKE '%' || :query || '%' ESCAPE '\'
            OR CAST(responseBody AS TEXT) LIKE '%' || :query || '%' ESCAPE '\'
        ORDER BY requestTime DESC
        LIMIT :limit
        """,
    )
    fun observeSummaries(query: String, limit: Int): Flow<List<CallSummaryRow>>

    @Query("SELECT * FROM call WHERE id = :id")
    fun observe(id: String): Flow<CallEntity?>

    @Query("SELECT * FROM call WHERE id IN (:ids) ORDER BY requestTime DESC")
    suspend fun get(ids: List<String>): List<CallEntity>

    @Query("DELETE FROM call WHERE id IN (:ids)")
    suspend fun delete(ids: List<String>)

    @Query("DELETE FROM call")
    suspend fun deleteAll()

    @Query("DELETE FROM call WHERE requestTime < :time")
    suspend fun deleteOlderThan(time: Long)

    @Query("DELETE FROM call WHERE id NOT IN (SELECT id FROM call ORDER BY requestTime DESC LIMIT :count)")
    suspend fun keepNewest(count: Int)
}

internal class HeadersConverter {
    private val serializer = MapSerializer(String.serializer(), ListSerializer(String.serializer()))

    @TypeConverter
    fun fromHeaders(headers: Map<String, List<String>>): String = Json.encodeToString(serializer, headers)

    @TypeConverter
    fun toHeaders(json: String): Map<String, List<String>> = Json.decodeFromString(serializer, json)
}
